# Generated by Django 4.2.16 on 2025-10-18 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="verification_token",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
